spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true